name: Framework

on:  
  push:
    branches: master
  pull_request:
    branches: master
        
jobs:
  build:
    name: Build .NET Framework
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2        
      - name: Restore NuGet packages
        run: nuget restore PlanReport.sln
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1      
      - name: Build The Solution
        run: msbuild PlanReport.sln
